=== chundonglinlin/ComEgg/old/MagicEgg/Environment/SCSBlog/network.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.magicegg.com/network" xmlns="http://www.magicegg.com/network" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:appinfo>
			<author>Goo Shoutrain</author>
			<filename>network.xsd</filename>
			<describe>				All interfaces must be defined here.
				Instance documents follow this must be named &quot;network.xml&quot;.</describe>
		</xs:appinfo>
	</xs:annotation>
<!--****************************************************************************************************-->
	<xs:include schemaLocation="types.xsd"/>
<!--****************************************************************************************************-->
	<xs:complexType final="restriction" name="network">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:sequence>
					<xs:element maxOccurs="unbounded" name="identity">
						<xs:complexType>
							<xs:attribute name="identity" type="unique_name" use="required"/>
							<xs:attribute name="pdu" type="reference_name" use="required"/>
							<xs:attribute name="direction" type="direction" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="command_id" type="reference_name" use="required">
					<xs:annotation>
						<xs:documentation>							It&apos;s one of fields in head.
							It identifis which pdu in the protocols.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute default="reference_name" name="size_id"/>
				<xs:attribute default="0" name="local_port" type="port"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
<!--****************************************************************************************************-->
	<xs:complexType final="#all" name="connector">
		<xs:complexContent>
			<xs:extension base="network">
				<xs:attribute name="remote_ip" type="ip" use="required"/>
				<xs:attribute name="remote_port" type="port" use="required"/>
				<xs:attribute default="0" name="reconnect" type="xs:nonNegativeInteger"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
<!--****************************************************************************************************-->
	<xs:element name="networks">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base">
					<xs:sequence>
						<xs:element name="connector" type="connector"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chundonglinlin/ComEgg/Environment/network.xml
<?xml version="1.0" encoding="UTF-8"?>
<networks xmlns="http://www.comegg.com/network" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.comegg.com/network network.xsd">
	<acceptor name="weather_server" command_id="command" protocol="weather" local_port="8900" size_id="size" max_connections="100">
		<identity identity="weather_server.query_id" pdu="query" direction="in"/>
		<identity identity="weather_server.query_ack_id" pdu="query_ack" direction="out"/>
	</acceptor>
	<acceptor name="scsblog_server" command_id="command" protocol="scsblog" local_port="9000" size_id="size" max_connections="100">
		<identity identity="scsblog_server.RegisterUserID" pdu="RegisterUser" direction="in"/>
		<identity identity="scsblog_server.RegisterUserAckID" pdu="RegisterUserAck" direction="out"/>
		<identity identity="scsblog_server.VerifyUserID" pdu="VerifyUser" direction="in"/>
		<identity identity="scsblog_server.VerifyUserAckID" pdu="VerifyUserAck" direction="out"/>
		<identity identity="scsblog_server.UpdateUserInfoID" pdu="UpdateUserInfo" direction="in"/>
		<identity identity="scsblog_server.UpdateUserInfoAckID" pdu="UpdateUserInfoAck" direction="out"/>
		<identity identity="scsblog_server.GetUserInfoID" pdu="GetUserInfo" direction="in"/>
		<identity identity="scsblog_server.GetUserInfoAckID" pdu="GetUserInfoAck" direction="out"/>
		<identity identity="scsblog_server.AddBlogID" pdu="AddBlog" direction="in"/>
		<identity identity="scsblog_server.AddBlogAckID" pdu="AddBlogAck" direction="out"/>
		<identity identity="scsblog_server.AddCommentsID" pdu="AddComments" direction="in"/>
		<identity identity="scsblog_server.AddCommentsAckID" pdu="AddCommentsAck" direction="out"/>
		<identity identity="scsblog_server.GetBlogID" pdu="GetBlog" direction="in"/>
		<identity identity="scsblog_server.GetBlogAckID" pdu="GetBlogAck" direction="out"/>
		<identity identity="scsblog_server.GetBlogListByUserID" pdu="GetBlogListByUser" direction="in"/>
		<identity identity="scsblog_server.GetBlogListByUserAckID" pdu="GetBlogListByUserAck" direction="out"/>
		<identity identity="scsblog_server.GetBlogListID" pdu="GetBlogList" direction="in"/>
		<identity identity="scsblog_server.GetBlogListAckID" pdu="GetBlogListAck" direction="out"/>
		<identity identity="scsblog_server.OpenWeatherServerID" pdu="OpenWeatherServer" direction="in"/>
		<identity identity="scsblog_server.OpenWeatherServerAckID" pdu="OpenWeatherServerAck" direction="out"/>
	</acceptor>
</networks>

=== chundonglinlin/ComEgg/old/MagicEgg/Environment/SCSBlog/network.xml
<?xml version="1.0" encoding="UTF-8"?>
<networks xmlns="http://www.magicegg.com/network" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.magicegg.com/network network.xsd">
	<connector command_id="command" size_id="size" remote_ip="127.0.0.1" remote_port="9000">
		<identity identity="RegisterUserID" pdu="RegisterUser" direction="out"/>
		<identity identity="RegisterUserAckID" pdu="RegisterUserAck" direction="in"/>
		<identity identity="VerifyUserID" pdu="VerifyUser" direction="out"/>
		<identity identity="VerifyUserAckID" pdu="VerifyUserAck" direction="in"/>
		<identity identity="UpdateUserInfoID" pdu="UpdateUserInfo" direction="out"/>
		<identity identity="UpdateUserInfoAckID" pdu="UpdateUserInfoAck" direction="in"/>
		<identity identity="GetUserInfoID" pdu="GetUserInfo" direction="out"/>
		<identity identity="GetUserInfoAckID" pdu="GetUserInfoAck" direction="in"/>
		<identity identity="AddBlogID" pdu="AddBlog" direction="out"/>
		<identity identity="AddBlogAckID" pdu="AddBlogAck" direction="in"/>
		<identity identity="AddCommentsID" pdu="AddComments" direction="out"/>
		<identity identity="AddCommentsAckID" pdu="AddCommentsAck" direction="in"/>
		<identity identity="GetBlogID" pdu="GetBlog" direction="out"/>
		<identity identity="GetBlogAckID" pdu="GetBlogAck" direction="in"/>
		<identity identity="GetBlogListByUserID" pdu="GetBlogListByUser" direction="out"/>
		<identity identity="GetBlogListByUserAckID" pdu="GetBlogListByUserAck" direction="in"/>
		<identity identity="GetBlogListID" pdu="GetBlogList" direction="out"/>
		<identity identity="GetBlogListAckID" pdu="GetBlogListAck" direction="in"/>
		<identity identity="OpenWeatherServerID" pdu="OpenWeatherServer" direction="out"/>
		<identity identity="OpenWeatherServerAckID" pdu="OpenWeatherServerAck" direction="in"/>
	</connector>
</networks>
