=== chundonglinlin/ComEgg/Environment/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.comegg.com/protocol"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.comegg.com/protocol" elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:annotation>
        <xs:appinfo>
            <author>Rafael</author>
            <filename>protocol.xsd</filename>
            <describe>
                Used by binary protocols.
                Instance documents follow this must be same with the protocol's
                name.
            </describe>
        </xs:appinfo>
    </xs:annotation>
    <!--****************************************************************************************************-->
    <xs:include schemaLocation="types.xsd"/>
    <!--****************************************************************************************************-->
    <xs:complexType name="head">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="normal" type="normal"/>
                    <xs:element name="float" type="float"/>
                    <xs:element name="string" type="string"/>
                    <xs:element name="group" type="group"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="pdu">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="normal" type="normal"/>
                    <xs:element name="float" type="float"/>
                    <xs:element name="string" type="string"/>
                    <xs:element name="group" type="group"/>
                </xs:choice>
                <xs:attribute name="name" type="uniqueName" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="protocol">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:sequence>
                        <xs:element name="commandIdValue" type="vUb4"
                                    maxOccurs="unbounded"/>
                        <xs:element name="head" type="head"/>
                        <xs:element name="pdu" type="pdu"
                                    maxOccurs="unbounded"/>
                    </xs:sequence>
                    <xs:attribute name="name" type="normalName" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== chundonglinlin/ComEgg/old/MagicEgg/Environment/Weather/protocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<protocol xmlns="http://www.magicegg.com/protocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.magicegg.com/protocol protocol.xsd">
	<command_id_value name="query_id" value="1"/>
	<command_id_value name="query_ack_id" value="2"/>
	<head>
		<normal name="size" length="4" signed="false"/>
		<normal name="command" length="4" signed="false"/>
	</head>
	<pdu name="query">
		<string name="identity" size="16"/>
	</pdu>
	<pdu name="query_ack">
		<string name="content" size="256"/>
	</pdu>
</protocol>

=== chundonglinlin/ComEgg/Environment/scsblog.xml
<?xml version="1.0" encoding="UTF-8"?>
<protocol xmlns="http://www.comegg.com/protocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.comegg.com/protocol protocol.xsd" name="scsblog">
	<commandIdValue name="registerUserId" value="1"/>
	<commandIdValue name="registerUserAckId" value="2"/>
	<commandIdValue name="verifyUserId" value="3"/>
	<commandIdValue name="verifyUserAckId" value="4"/>
	<commandIdValue name="updateUserInfoId" value="5"/>
	<commandIdValue name="updateUserInfoAckId" value="6"/>
	<commandIdValue name="getUserInfoId" value="7"/>
	<commandIdValue name="getUserInfoAckId" value="8"/>
	<commandIdValue name="addBlogId" value="9"/>
	<commandIdValue name="addBlogAckId" value="10"/>
	<commandIdValue name="addCommentsId" value="11"/>
	<commandIdValue name="addCommentsAckId" value="12"/>
	<commandIdValue name="getBlogId" value="13"/>
	<commandIdValue name="getBlogAckId" value="14"/>
	<commandIdValue name="getBlogListByUserId" value="15"/>
	<commandIdValue name="getBlogListByUserAckId" value="16"/>
	<commandIdValue name="getBlogListId" value="17"/>
	<commandIdValue name="getBlogListAckId" value="18"/>
	<commandIdValue name="openWeatherServerId" value="19"/>
	<commandIdValue name="openWeatherServerAckId" value="20"/>
	<head>
		<normal name="size" length="4" signed="false"/>
		<normal name="command" length="4" signed="false"/>
	</head>
	<pdu name="registerUser">
		<string name="userName" size="16"/>
		<string name="password" size="16"/>
	</pdu>
	<pdu name="registerUserAck">
		<normal name="userId" length="4" signed="false"/>
	</pdu>
	<pdu name="verifyUser">
		<string name="userName" size="16"/>
		<string name="password" size="16"/>
	</pdu>
	<pdu name="verifyUserAck">
		<normal name="userId" length="4" signed="false"/>
	</pdu>
	<pdu name="updateUserInfo">
		<normal name="userId" length="4" signed="false"/>
		<normal name="ssMale" length="1"/>
		<string name="birthday" size="11"/>
		<string name="selfEstimate" size="128"/>
	</pdu>
	<pdu name="updateUserInfoAck">
		<normal name="result" length="1"/>
	</pdu>
	<pdu name="getUserInfo">
		<normal name="userId" length="4" signed="false"/>
	</pdu>
	<pdu name="getUserInfoAck">
		<normal name="result" length="1"/>
		<normal name="isMale" length="1"/>
		<string name="birthday" size="11"/>
		<string name="selfEstimate" size="128"/>
	</pdu>
	<pdu name="addBlog">
		<string name="blogTitle" size="32"/>
		<string name="blogContent" size="255"/>
	</pdu>
	<pdu name="addBlogAck">
		<normal name="result" length="1"/>
	</pdu>
	<pdu name="addComments">
		<normal name="blogId" length="4" signed="false"/>
		<string name="comments" size="128"/>
	</pdu>
	<pdu name="addCommentsAck">
		<normal name="result" length="1"/>
	</pdu>
	<pdu name="getBlog">
		<normal name="blogId" length="4" signed="false"/>
	</pdu>
	<pdu name="getBlogAck">
		<normal name="result" length="1"/>
		<string name="userName" size="16"/>
		<string name="blogTitle" size="32"/>
		<string name="blogContent" size="255"/>
		<string name="createTime" size="20"/>
		<normal name="commentsNum" length="4" signed="false"/>
		<group name="commentsArray" size="commentsNum">
			<normal name="userID" length="4" signed="false"/>
			<string name="userName" size="16"/>
			<string name="blogComments" size="128"/>
			<string name="createTime" size="20"/>
		</group>
	</pdu>
	<pdu name="getBlogListByUser">
		<normal name="userID" length="4" signed="false"/>
	</pdu>
	<pdu name="getBlogListByUserAck">
		<normal name="result" length="1"/>
		<normal name="blogNum" length="4" signed="false"/>
		<group name="blogArray" size="blogNum">
			<normal name="blogID" length="4" signed="false"/>
			<string name="blogTitle" size="32"/>
			<string name="createTime" size="20"/>
		</group>
	</pdu>
	<pdu name="getBlogList"/>
	<pdu name="getBlogListAck">
		<normal name="result" length="1"/>
		<normal name="blogNum" length="4" signed="false"/>
		<group name="blogArray" size="blogNum">
			<normal name="userID" length="4" signed="false"/>
			<string name="userName" size="16"/>
			<normal name="blogID" length="4" signed="false"/>
			<string name="blogTitle" size="32"/>
			<string name="createTime" size="20"/>
		</group>
	</pdu>
	<pdu name="openWeatherServer"/>
	<pdu name="openWeatherServerAck">
		<normal name="Result" length="1"/>
	</pdu>	
</protocol>
