=== chundonglinlin/ComEgg/Environments/Weather/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.comegg.com/module" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.comegg.com/module" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:appinfo>
			<author>Goo Shoutrain</author>
			<filename>interface.xsd</filename>
			<describe>
				All interfaces must be defined here.
				Instance documents follow this must be named "module.xml".
			</describe>
		</xs:appinfo>
	</xs:annotation>
	<!--****************************************************************************************************-->
	<xs:include schemaLocation="types.xsd"/>
	<!--****************************************************************************************************-->
	<xs:complexType name="parameter">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="normal" type="normal"/>
					<xs:element name="float" type="float"/>
					<xs:element name="string" type="string"/>
					<xs:element name="group" type="group"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="interface">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:sequence>
					<xs:element name="parameter_in" type="parameter" minOccurs="0"/>
					<xs:element name="parameter_out" type="parameter" minOccurs="0"/>				
				</xs:sequence>
				<xs:attribute name="name" type="normal_name" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="module">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:sequence>
					<xs:element name="interface" type="interface" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="path" type="xs:string" use="required"/>
				<xs:attribute name="name" type="unique_name" use="required"/>
				<xs:attribute name="ext" type="xs:string" default="so"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="modules">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base">
					<xs:sequence>	
						<xs:element name="module" type="module" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chundonglinlin/ComEgg/env/xml/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<modules xmlns="http://www.comegg.com/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.comegg.com/module module.xsd">
	<module path="./Plugin" name="SCSBlog" ext="so">
		<interface name="RegisterUser">
			<parameter_in>
				<string name="szUserName" size="16"/>
				<string name="szPassword" size="16"/>
			</parameter_in>
			<parameter_out>
				<normal name="uiUserID" length="4" signed="false"/>
			</parameter_out>
		</interface>
		<interface name="VerifyUser">
			<parameter_in>
				<string name="szUserName" size="16"/>
				<string name="szPassword" size="16"/>
			</parameter_in>
			<parameter_out>
				<normal name="uiUserID" length="4" signed="false"/>
			</parameter_out>
		</interface>
		<interface name="UpdateUserInfo">
			<parameter_in>
				<normal name="uiUserID" length="4" signed="false"/>
				<normal name="bIsMale" length="1"/>
				<string name="szBirthday" size="11"/>
				<string name="szSelfEstimate" size="128"/>
			</parameter_in>
			<parameter_out>
				<normal name="bResult" length="1"/>
			</parameter_out>
		</interface>
		<interface name="GetUserInfo">
			<parameter_in>
				<normal name="uiUserID" length="4" signed="false"/>
			</parameter_in>
			<parameter_out>
				<normal name="bResult" length="1"/>
				<normal name="bIsMale" length="1"/>
				<string name="szBirthday" size="11"/>
				<string name="szSelfEstimate" size="128"/>
			</parameter_out>
		</interface>
		<interface name="AddBlog">
			<parameter_in>
				<normal name="uiUserID" length="4" signed="false"/>
				<string name="szBlogTitle" size="32"/>
				<string name="szBlogContent" size="255"/>
			</parameter_in>
			<parameter_out>
				<normal name="bResult" length="1"/>
			</parameter_out>
		</interface>
		<interface name="AddComments">
			<parameter_in>
				<normal name="uiBlogID" length="4" signed="false"/>
				<normal name="uiUserID" length="4" signed="false"/>
				<string name="szComments" size="128"/>
			</parameter_in>
			<parameter_out>
				<normal name="bResult" length="1"/>
			</parameter_out>
		</interface>
		<interface name="GetBlog">
			<parameter_in>
				<normal name="uiBlogID" length="4" signed="false"/>
			</parameter_in>
			<parameter_out>
				<normal name="uiSize" length="4" signed="false"/>
				<normal name="bResult" length="1"/>
				<string name="szUserName" size="16"/>
				<string name="szBlogTitle" size="32"/>
				<string name="szBlogContent" size="255"/>
				<string name="szCreateTime" size="20"/>
				<normal name="uiCommentsNum" length="4" signed="false"/>
				<group name="pCommentsArray" size="uiCommentsNum">
					<normal name="uiUserID" length="4" signed="false"/>
					<string name="szUserName" size="16"/>
					<string name="szBlogComments" size="128"/>
					<string name="szCreateTime" size="20"/>
				</group>
			</parameter_out>
		</interface>
		<interface name="GetBlogListByUser">
			<parameter_in>
				<normal name="uiUserID" length="4" signed="false"/>
			</parameter_in>
			<parameter_out>
				<normal name="uiSize" length="4" signed="false"/>
				<normal name="bResult" length="1"/>
				<normal name="uiBlogNum" length="4" signed="false"/>
				<group name="pBlogArray" size="uiBlogNum">
					<normal name="uiBlogID" length="4" signed="false"/>
					<string name="szBlogTitle" size="32"/>
					<string name="szCreateTime" size="20"/>
				</group>
			</parameter_out>
		</interface>
		<interface name="GetBlogList">
			<parameter_out>
				<normal name="uiSize" length="4" signed="false"/>
				<normal name="bResult" length="1"/>
				<normal name="uiBlogNum" length="4" signed="false"/>
				<group name="pBlogArray" size="uiBlogNum">
					<normal name="uiUserID" length="4" signed="false"/>
					<string name="szUserName" size="16"/>
					<normal name="uiBlogID" length="4" signed="false"/>
					<string name="szBlogTitle" size="32"/>
					<string name="szCreateTime" size="20"/>
				</group>
			</parameter_out>
		</interface>
	</module>
</modules>
