=== chundonglinlin/ComEgg/env/xml/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	targetNamespace="http://www.comegg.com/protocol"
	xmlns="http://www.comegg.com/protocol"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:appinfo>
			<author>Goo Shoutrain</author>
			<filename>protocol.xsd</filename>
			<describe>
				Used by binary protocols. Instance decuments follow this must be same with the protocol's
				name.
			</describe>
		</xs:appinfo>
	</xs:annotation>
	<!--****************************************************************************************************-->
	<xs:include schemaLocation="types.xsd"/>
	<!--****************************************************************************************************-->
	<xs:complexType name="head">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="normal" type="normal"/>
					<xs:element name="float" type="float"/>
					<xs:element name="string" type="string"/>
					<xs:element name="group" type="group"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="pdu">
		<xs:complexContent>
			<xs:extension base="base">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element name="normal" type="normal"/>
					<xs:element name="float" type="float"/>
					<xs:element name="string" type="string"/>
					<xs:element name="group" type="group"/>
				</xs:choice>
				<xs:attribute name="name" type="unique_name" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="protocol">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="base">
					<xs:sequence>
						<xs:element name="command_id_value" type="v_ub_4" maxOccurs="unbounded"/>
						<xs:element name="head" type="head"/>
						<xs:element name="pdu" type="pdu" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="name" type="normal_name" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== chundonglinlin/ComEgg/old/MagicEgg/Environment/SCSBlog/protocol.xml
<?xml version="1.0" encoding="UTF-8"?>
<protocol xmlns="http://www.magicegg.com/protocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.magicegg.com/protocol protocol.xsd">
	<command_id_value name="RegisterUserID" value="1"/>
	<command_id_value name="RegisterUserAckID" value="2"/>
	<command_id_value name="VerifyUserID" value="3"/>
	<command_id_value name="VerifyUserAckID" value="4"/>
	<command_id_value name="UpdateUserInfoID" value="5"/>
	<command_id_value name="UpdateUserInfoAckID" value="6"/>
	<command_id_value name="GetUserInfoID" value="7"/>
	<command_id_value name="GetUserInfoAckID" value="8"/>
	<command_id_value name="AddBlogID" value="9"/>
	<command_id_value name="AddBlogAckID" value="10"/>
	<command_id_value name="AddCommentsID" value="11"/>
	<command_id_value name="AddCommentsAckID" value="12"/>
	<command_id_value name="GetBlogID" value="13"/>
	<command_id_value name="GetBlogAckID" value="14"/>
	<command_id_value name="GetBlogListByUserID" value="15"/>
	<command_id_value name="GetBlogListByUserAckID" value="16"/>
	<command_id_value name="GetBlogListID" value="17"/>
	<command_id_value name="GetBlogListAckID" value="18"/>
	<command_id_value name="OpenWeatherServerID" value="19"/>
	<command_id_value name="OpenWeatherServerAckID" value="20"/>
	<head>
		<normal name="size" length="4" signed="false"/>
		<normal name="command" length="4" signed="false"/>
	</head>
	<pdu name="RegisterUser">
		<string name="UserName" size="16"/>
		<string name="Password" size="16"/>
	</pdu>
	<pdu name="RegisterUserAck">
		<normal name="UserID" length="4" signed="false"/>
	</pdu>
	<pdu name="VerifyUser">
		<string name="UserName" size="16"/>
		<string name="Password" size="16"/>
	</pdu>
	<pdu name="VerifyUserAck">
		<normal name="UserID" length="4" signed="false"/>
	</pdu>
	<pdu name="UpdateUserInfo">
		<normal name="UserID" length="4" signed="false"/>
		<normal name="IsMale" length="1"/>
		<string name="Birthday" size="11"/>
		<string name="SelfEstimate" size="128"/>
	</pdu>
	<pdu name="UpdateUserInfoAck">
		<normal name="Result" length="1"/>
	</pdu>
	<pdu name="GetUserInfo">
		<normal name="UserID" length="4" signed="false"/>
	</pdu>
	<pdu name="GetUserInfoAck">
		<normal name="Result" length="1"/>
		<normal name="IsMale" length="1"/>
		<string name="Birthday" size="11"/>
		<string name="SelfEstimate" size="128"/>
	</pdu>
	<pdu name="AddBlog">
		<string name="BlogTitle" size="32"/>
		<string name="BlogContent" size="255"/>
	</pdu>
	<pdu name="AddBlogAck">
		<normal name="Result" length="1"/>
	</pdu>
	<pdu name="AddComments">
		<normal name="BlogID" length="4" signed="false"/>
		<string name="Comments" size="128"/>
	</pdu>
	<pdu name="AddCommentsAck">
		<normal name="Result" length="1"/>
	</pdu>
	<pdu name="GetBlog">
		<normal name="BlogID" length="4" signed="false"/>
	</pdu>
	<pdu name="GetBlogAck">
		<normal name="Result" length="1"/>
		<string name="UserName" size="16"/>
		<string name="BlogTitle" size="32"/>
		<string name="BlogContent" size="255"/>
		<string name="CreateTime" size="20"/>
		<normal name="CommentsNum" length="4" signed="false"/>
		<group name="CommentsArray" size="CommentsNum">
			<normal name="UserID" length="4" signed="false"/>
			<string name="UserName" size="16"/>
			<string name="BlogComments" size="128"/>
			<string name="CreateTime" size="20"/>
		</group>
	</pdu>
	<pdu name="GetBlogListByUser">
		<normal name="UserID" length="4" signed="false"/>
	</pdu>
	<pdu name="GetBlogListByUserAck">
		<normal name="Result" length="1"/>
		<normal name="BlogNum" length="4" signed="false"/>
		<group name="BlogArray" size="BlogNum">
			<normal name="BlogID" length="4" signed="false"/>
			<string name="BlogTitle" size="32"/>
			<string name="CreateTime" size="20"/>
		</group>
	</pdu>
	<pdu name="GetBlogList"/>
	<pdu name="GetBlogListAck">
		<normal name="Result" length="1"/>
		<normal name="BlogNum" length="4" signed="false"/>
		<group name="BlogArray" size="BlogNum">
			<normal name="UserID" length="4" signed="false"/>
			<string name="UserName" size="16"/>
			<normal name="BlogID" length="4" signed="false"/>
			<string name="BlogTitle" size="32"/>
			<string name="CreateTime" size="20"/>
		</group>
	</pdu>
	<pdu name="OpenWeatherServer"/>
	<pdu name="OpenWeatherServerAck">
		<normal name="Result" length="1"/>
	</pdu>	
</protocol>
